"""empty message

Revision ID: 121a8b06037c
Revises: 0e31a2bd8d39
Create Date: 2024-11-20 12:43:55.416778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "121a8b06037c"
down_revision: Union[str, None] = "0e31a2bd8d39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("supply_user_id_fkey", "supply", type_="foreignkey")
    op.drop_column("supply", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supply",
        sa.Column(
            "user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key("supply_user_id_fkey", "supply", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
