"""empty message

Revision ID: 549dc3ae9246
Revises: 
Create Date: 2024-10-23 10:44:19.939205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "549dc3ae9246"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("telephone_number", sa.String(length=32), nullable=True),
        sa.Column("address", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_provider_id"), "provider", ["id"], unique=True)
    op.create_table(
        "storage",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=256), nullable=False),
        sa.Column("max_weight", sa.Float(), nullable=False),
        sa.Column("max_quantity", sa.Integer(), nullable=False),
        sa.Column("storing_weight", sa.Float(), server_default="0", nullable=True),
        sa.Column("storing_quantity", sa.Integer(), server_default="0", nullable=True),
        sa.Column("last_restock_dt", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_storage_id"), "storage", ["id"], unique=True)
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("provider_price", sa.Float(), nullable=False),
        sa.Column("sell_price", sa.Float(), nullable=False),
        sa.Column("available_weight", sa.Float(), nullable=True),
        sa.Column("available_quantity", sa.Integer(), nullable=True),
        sa.Column("delivery_dt", sa.DateTime(), nullable=True),
        sa.Column("expiration_dt", sa.DateTime(), nullable=True),
        sa.Column("provider_id", sa.String(length=36), nullable=False),
        sa.Column("storage", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storage"],
            ["storage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_storage_id"), table_name="storage")
    op.drop_table("storage")
    op.drop_index(op.f("ix_provider_id"), table_name="provider")
    op.drop_table("provider")
    # ### end Alembic commands ###
